// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIawtdELnDWPsh8I7uDcgF2q6HFR_DGkw',
    appId: '1:806417881380:web:d10f26d2f44acb39833bb1',
    messagingSenderId: '806417881380',
    projectId: 'rentalyze-app',
    authDomain: 'rentalyze-app.firebaseapp.com',
    storageBucket: 'rentalyze-app.firebasestorage.app',
    measurementId: 'G-G9Q0LN63HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgJTfAP8Q7eZ9X1234567890ABCDEFGHIJ',
    appId: '1:806417881380:android:1234567890abcdef833bb1',
    messagingSenderId: '806417881380',
    projectId: 'rentalyze-app',
    storageBucket: 'rentalyze-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgJTfAP8Q7eZ9X1234567890ABCDEFGHIJ',
    appId: '1:806417881380:ios:1234567890abcdef833bb1',
    messagingSenderId: '806417881380',
    projectId: 'rentalyze-app',
    storageBucket: 'rentalyze-app.firebasestorage.app',
    iosBundleId: 'com.rentalyze.rentalyze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgJTfAP8Q7eZ9X1234567890ABCDEFGHIJ',
    appId: '1:806417881380:macos:1234567890abcdef833bb1',
    messagingSenderId: '806417881380',
    projectId: 'rentalyze-app',
    storageBucket: 'rentalyze-app.firebasestorage.app',
    iosBundleId: 'com.rentalyze.rentalyze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgJTfAP8Q7eZ9X1234567890ABCDEFGHIJ',
    appId: '1:806417881380:windows:1234567890abcdef833bb1',
    messagingSenderId: '806417881380',
    projectId: 'rentalyze-app',
    authDomain: 'rentalyze-app.firebaseapp.com',
    storageBucket: 'rentalyze-app.firebasestorage.app',
    measurementId: 'G-G9Q0LN63HH',
  );
}
