name: Deploy to Firebase Hosting (Disabled - Need Token)

on:
  # Temporarily disabled until FIREBASE_TOKEN is configured
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Web App
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.4'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Enable web platform
      run: flutter config --enable-web
      
    - name: Build web app
      run: flutter build web --release --base-href "/"
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.4'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Enable web platform
      run: flutter config --enable-web
      
    - name: Build web app
      run: flutter build web --release
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Deploy to Firebase Hosting Preview
      run: firebase hosting:channel:deploy preview-${{ github.event.number }} --expires 7d --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}